package ServerInterface;


/**
* ServerInterface/ServerObjectInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Monday, March 3, 2025 3:55:10 PM EST
*/

public abstract class ServerObjectInterfacePOA extends org.omg.PortableServer.Servant
 implements ServerInterface.ServerObjectInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addShare", new java.lang.Integer (0));
    _methods.put ("removeShare", new java.lang.Integer (1));
    _methods.put ("listShareAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseShare", new java.lang.Integer (3));
    _methods.put ("getShares", new java.lang.Integer (4));
    _methods.put ("sellShare", new java.lang.Integer (5));
    _methods.put ("swapShare", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // admin
       case 0:  // ServerInterface/ServerObjectInterface/addShare
       {
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addShare (shareID, shareType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerInterface/ServerObjectInterface/removeShare
       {
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         String $result = null;
         $result = this.removeShare (shareID, shareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerInterface/ServerObjectInterface/listShareAvailability
       {
         String shareType = in.read_string ();
         String $result = null;
         $result = this.listShareAvailability (shareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // buyer
       case 3:  // ServerInterface/ServerObjectInterface/purchaseShare
       {
         String buyerID = in.read_string ();
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         int shareCount = in.read_long ();
         String $result = null;
         $result = this.purchaseShare (buyerID, shareID, shareType, shareCount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerInterface/ServerObjectInterface/getShares
       {
         String buyerID = in.read_string ();
         String $result = null;
         $result = this.getShares (buyerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ServerInterface/ServerObjectInterface/sellShare
       {
         String buyerID = in.read_string ();
         String shareID = in.read_string ();
         int shareCount = in.read_long ();
         String $result = null;
         $result = this.sellShare (buyerID, shareID, shareCount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ServerInterface/ServerObjectInterface/swapShare
       {
         String buyerID = in.read_string ();
         String newShareID = in.read_string ();
         String newShareType = in.read_string ();
         String oldShareID = in.read_string ();
         String oldShareType = in.read_string ();
         String $result = null;
         $result = this.swapShare (buyerID, newShareID, newShareType, oldShareID, oldShareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ServerInterface/ServerObjectInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerInterface/ServerObjectInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerObjectInterface _this() 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object());
  }

  public ServerObjectInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerObjectInterfacePOA
