package ServerInterface;


/**
* ServerInterface/ServerObjectInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Monday, March 3, 2025 3:55:10 PM EST
*/

abstract public class ServerObjectInterfaceHelper
{
  private static String  _id = "IDL:ServerInterface/ServerObjectInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerInterface.ServerObjectInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerInterface.ServerObjectInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerInterface.ServerObjectInterfaceHelper.id (), "ServerObjectInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerInterface.ServerObjectInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerObjectInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerInterface.ServerObjectInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerInterface.ServerObjectInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerInterface.ServerObjectInterface)
      return (ServerInterface.ServerObjectInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerInterface._ServerObjectInterfaceStub stub = new ServerInterface._ServerObjectInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerInterface.ServerObjectInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerInterface.ServerObjectInterface)
      return (ServerInterface.ServerObjectInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerInterface._ServerObjectInterfaceStub stub = new ServerInterface._ServerObjectInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
