package ServerInterface;


/**
* ServerInterface/ServerObjectInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Monday, March 3, 2025 3:55:10 PM EST
*/

public interface ServerObjectInterfaceOperations 
{

  // admin
  String addShare (String shareID, String shareType, int capacity);
  String removeShare (String shareID, String shareType);
  String listShareAvailability (String shareType);

  // buyer
  String purchaseShare (String buyerID, String shareID, String shareType, int shareCount);
  String getShares (String buyerID);
  String sellShare (String buyerID, String shareID, int shareCount);
  String swapShare (String buyerID, String newShareID, String newShareType, String oldShareID, String oldShareType);
  void shutdown ();
} // interface ServerObjectInterfaceOperations
