package ServerInterface;

/**
* ServerInterface/ServerObjectInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Monday, March 3, 2025 3:55:10 PM EST
*/

public final class ServerObjectInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerInterface.ServerObjectInterface value = null;

  public ServerObjectInterfaceHolder ()
  {
  }

  public ServerObjectInterfaceHolder (ServerInterface.ServerObjectInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerInterface.ServerObjectInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerInterface.ServerObjectInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerInterface.ServerObjectInterfaceHelper.type ();
  }

}
